<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>localization</name>
  <version>0.0.0</version>
  <description>Localization and Bringup package</description>
  <maintainer email="sameh@todo.todo">sameh</maintainer>
  <license>Apache-2.0</license>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>turtlebot3_gazebo</exec_depend>
  <exec_depend>turtlebot3_navigation2</exec_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
